# Generated by Django 4.1 on 2022-10-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_employee_customuser_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Customer', 'Customer')], max_length=255, null=True, verbose_name='Role'),
        ),
    ]
