# Generated by Django 4.1 on 2022-10-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Last Name')),
                ('dob', models.DateField(null=True, verbose_name='DOB')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6, null=True, verbose_name='Gender')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('address1', models.TextField(null=True, verbose_name='Address')),
                ('address2', models.TextField(null=True, verbose_name='Address')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('pincode', models.CharField(max_length=6, null=True, verbose_name='Pincode')),
                ('contect', models.CharField(max_length=10, null=True, verbose_name='Contect Number')),
                ('adhar', models.BigIntegerField(null=True, verbose_name='Adhar Number')),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=25, null=True, verbose_name='Last Name')),
                ('dob', models.DateField(null=True, verbose_name='Date of birth')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6, verbose_name='Gender')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image', verbose_name='Image')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(max_length=50, null=True, verbose_name='Address')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='State')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='City')),
                ('pincode', models.CharField(max_length=6, null=True, verbose_name='Pincode')),
                ('phone_number', models.CharField(max_length=10, null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name_plural': 'Employe',
            },
        ),
        migrations.CreateModel(
            name='Employe_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=20, null=True, verbose_name='Role title')),
            ],
            options={
                'verbose_name_plural': 'Employe role',
            },
        ),
        migrations.CreateModel(
            name='Hall_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_type', models.CharField(max_length=20, null=True, verbose_name='Hall Type')),
            ],
            options={
                'verbose_name_plural': 'Hall type',
            },
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Hall Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Image', verbose_name='Hall Image')),
                ('price', models.FloatField(max_length=6, null=True, verbose_name='Hall price')),
                ('capacity', models.CharField(max_length=20, null=True, verbose_name='Capacity')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('owner_name', models.CharField(max_length=15, null=True, verbose_name='Owner Name')),
                ('owner_phone', models.CharField(max_length=10, null=True, verbose_name='Owner Phone Number')),
                ('owner_email', models.EmailField(max_length=254, null=True, verbose_name='Owner Email')),
                ('employe', models.ManyToManyField(to='hall.employe')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.hall_type')),
            ],
            options={
                'verbose_name_plural': 'Halls',
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.employe_role'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='User Name')),
                ('booked_on', models.DateField(null=True, verbose_name='Booked On')),
                ('booking_date', models.DateField(null=True, verbose_name='Booking Date')),
                ('arrival_date', models.DateField(null=True, verbose_name='Arrival Date')),
                ('leaving_date', models.DateField(null=True, verbose_name='Leaving Date')),
                ('booking_parpus', models.CharField(max_length=15, null=True, verbose_name='Booking Parpus')),
                ('status', models.CharField(max_length=15, null=True, verbose_name='Status')),
                ('custmor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.customer')),
                ('hall_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.halls')),
            ],
            options={
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, null=True, verbose_name='User Name')),
                ('hall_charge', models.FloatField(null=True, verbose_name='Hall Charge')),
                ('payment_date', models.DateField(null=True, verbose_name='Pyment Date')),
                ('payment_mode', models.CharField(max_length=10, null=True, verbose_name='Payment Mode')),
                ('booking_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.booking')),
                ('custmor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.customer')),
            ],
            options={
                'verbose_name_plural': 'Bill',
            },
        ),
    ]
