# Generated by Django 4.1 on 2022-10-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_remove_employe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
