# Generated by Django 4.1 on 2022-10-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_remove_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='last_name',
        ),
    ]
