# Generated by Django 4.1 on 2022-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_customer_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hall_name',
            field=models.CharField(max_length=100, null=True, verbose_name='User Name'),
        ),
    ]
