# Generated by Django 4.1 on 2022-10-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_remove_customer_country_remove_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halls',
            name='employe',
        ),
        migrations.AddField(
            model_name='halls',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.employe'),
        ),
    ]
