# Generated by Django 4.1 on 2022-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_remove_halls_employe_halls_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='booking_id',
            field=models.CharField(max_length=100, null=True, verbose_name='booking_id'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='custmor',
            field=models.CharField(max_length=100, null=True, verbose_name='custmor'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(max_length=100, null=True, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user_name',
            field=models.CharField(max_length=100, null=True, verbose_name='User Name'),
        ),
    ]
